apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
  annotations:
    cloud.google.com/neg: '{"ingress": true}'  # Network Endpoint Group for GCP load balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend

